# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 13:00
from __future__ import unicode_literals

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='Juan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(default='/covers/default_cover.jpeg', null=True, upload_to=books.models.cover_upload_path),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
