# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 13:01
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180112_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country',
            field=django_countries.fields.CountryField(default='Argentina', max_length=2),
            preserve_default=False,
        ),
    ]
