# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('av', 'Available'), ('ret', 'Retired'), ('res', 'Reserved')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
