# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_back', models.DateField()),
                ('status', models.CharField(choices=[('av', 'Available'), ('ret', 'Retirado'), ('res', 'Reserved')], max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='books.BookInstance')),
            ],
        ),
    ]
